package fi.helsinki.cs.tmc.ui.swingPanels;

import fi.helsinki.cs.tmc.controller.Controller;
import fi.helsinki.cs.tmc.controller.IController;

/**
 * this panel has two buttons: "Test all" and "Send". NetBeans takes this panel
 * and puts it alongside the other buttons.
 * @author jmturpei
 */
public class TestAndSendPanel extends javax.swing.JPanel {

    private IController controller;

    /** Creates new form TestAndSendPanel */
    public TestAndSendPanel() {
        initComponents();

        controller = Controller.getInstance();

        jButton1.addActionListener(new java.awt.event.ActionListener() {

            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controller.send(jButton1);
            }
        });

        jButton2.addActionListener(new java.awt.event.ActionListener() {

            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controller.runTests();
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jButton1.setText(org.openide.util.NbBundle.getMessage(TestAndSendPanel.class, "TestAndSendPanel.jButton1.text")); // NOI18N

        jButton2.setText(org.openide.util.NbBundle.getMessage(TestAndSendPanel.class, "TestAndSendPanel.jButton2.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1)
                .addComponent(jButton2))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
