package fi.helsinki.cs.tmc.ui;

import javax.swing.JPanel;

public class LongTextDisplayPanel extends JPanel {

    public LongTextDisplayPanel(String htmlText) {
        initComponents();
        editorPane.setText(htmlText);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        editorPane = new javax.swing.JEditorPane();

        setMinimumSize(new java.awt.Dimension(640, 400));
        setPreferredSize(new java.awt.Dimension(640, 400));
        setLayout(new java.awt.BorderLayout());

        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        editorPane.setContentType(org.openide.util.NbBundle.getMessage(LongTextDisplayPanel.class, "LongTextDisplayPanel.editorPane.contentType")); // NOI18N
        editorPane.setEditable(false);
        editorPane.setFont(new java.awt.Font("Monospaced", 0, 12));
        scrollPane.setViewportView(editorPane);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane editorPane;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
