package fi.helsinki.cs.tmc.ui;

import java.awt.Frame;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;
import org.openide.util.Cancellable;
import org.openide.windows.WindowManager;

public class SubmissionResultWaitingDialog extends JDialog implements SubmissionProgressView {

    public static SubmissionResultWaitingDialog createAndShow() {
        final SubmissionResultWaitingDialog dialog = new SubmissionResultWaitingDialog(WindowManager.getDefault().getMainWindow());
        dialog.setLocationRelativeTo(null);
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);
        return dialog;
    }
    
    private Cancellable task;
    
    /** Creates new form SubmissionResultWaitingDialog */
    private SubmissionResultWaitingDialog(Frame parent) {
        super(parent, false);
        initComponents();
        queueLabel.setVisible(false);
    }

    @Override
    public void setPositionInQueueFromAnyThread(final int position) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                if (position > 1) {
                    queueLabel.setText("Place in queue: " + position);
                    queueLabel.setVisible(true);
                } else {
                    queueLabel.setVisible(false);
                }
            }
        });
    }

    public void setTask(Cancellable task) {
        this.task = task;
        cancelButton.setEnabled(task != null);
    }
    
    public void close() {
        setVisible(false);
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        waitingLabel = new javax.swing.JLabel();
        queueLabel = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        waitingLabel.setText(org.openide.util.NbBundle.getMessage(SubmissionResultWaitingDialog.class, "SubmissionResultWaitingDialog.waitingLabel.text")); // NOI18N

        queueLabel.setText(org.openide.util.NbBundle.getMessage(SubmissionResultWaitingDialog.class, "SubmissionResultWaitingDialog.queueLabel.text")); // NOI18N

        backgroundLabel.setText(org.openide.util.NbBundle.getMessage(SubmissionResultWaitingDialog.class, "SubmissionResultWaitingDialog.backgroundLabel.text")); // NOI18N
        backgroundLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backgroundLabelActionPerformed(evt);
            }
        });

        jProgressBar1.setIndeterminate(true);

        cancelButton.setText(org.openide.util.NbBundle.getMessage(SubmissionResultWaitingDialog.class, "SubmissionResultWaitingDialog.cancelButton.text")); // NOI18N
        cancelButton.setEnabled(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(queueLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backgroundLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(waitingLabel)
                        .addContainerGap(231, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(waitingLabel)
                .addGap(12, 12, 12)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(queueLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(backgroundLabel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backgroundLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backgroundLabelActionPerformed
        close();
    }//GEN-LAST:event_backgroundLabelActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        task.cancel();
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backgroundLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel queueLabel;
    private javax.swing.JLabel waitingLabel;
    // End of variables declaration//GEN-END:variables
}
